/**
 * Real product photography, keyed by product slug.
 *
 * GENERATED by scripts/assets/ingest-product-images.mjs — do not edit by hand.
 * Consumed by src/lib/brand.ts (BRAND.productImageOverrides), which
 * src/lib/shopflow/mock.ts applies over the placeholder imagery.
 *
 * Empty until the first batch of real photos is ingested.
 */
export const PRODUCT_PHOTOS: Record<string, string[]> = {};
